### ISSUE TITLE
postgres_rds_terraform - Run npm package

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/MicroService#25]
When the RDS DB is created a npm package should be run 

NPM Package
https://www.npmjs.com/package/map-pluto-postgres

Source Code 
https://github.com/stuartshay/NavigatorDataStore/tree/master/scripts/map-pluto-postgres
(Details on Page)

**Note:**  I did not test package the columns in the feed do change, package might required to be fixed.

**Comment by xmavrck** [comment]
@stuartshay  the above package is not working. although the terraform script is ready it's having trouble, because of the missing public. pluto and some other required things, database, and schema. can you have a look at it? let me know when the package is fixed, meanwhile, I will work on the other tasks.
